### ISSUE TITLE
Default font is terrible

### ISSUE THREAD

**Issue by Timmmm** [snapcrafters/vscode#23]
![screenshot from 2018-10-28 18-59-09](https://user-images.githubusercontent.com/376842/47620589-9199b080-dae3-11e8-973f-1d90263ccec0.png)

That makes my eyes hurt. The rest of the system's fonts are surprisingly ok. This is on a completely fresh Ubuntu 18.10 install.

The font preferences say: `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'`.

According to the Fonts app I don't have Droid Sans Mono installed by I do have Droid Sans Fallback whatever that is.

**Comment by Timmmm** [comment]
Changing the font preference to 'Noto Mono' gives something much less insane.

**Comment by popey** [comment]
Thanks for the issue report. This looks similar to the upstream reported bug filed at https://github.com/Microsoft/vscode/issues/5742 . We can't shop Droid Sans Mono because this package builds on 16.04 which doesn't contain the font. We could potentially ship that font, but it's probably preferable to use a different one which is supported. We could certainly ship Noto Mono (which as I understand it is the replacement), and set the default to that in this package. Would that be a suitable fix?

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/vscode/pull/40
