### ISSUE TITLE
HOME folder is wrong

### ISSUE THREAD

**Issue by jackTaw88** [snapcrafters/vscode#36]
Vscode normally should use this directory as HOME:

/home/user_name/snap/vscode

But vscode (snap packaged version) use default user's home folder which is:

/home/user_name

Can you please fix this issue?

Thank you

**Comment by Kedstar99** [comment]
Why is this an issue? This is by design.


Classic confinement is effectively un-confining the applications inside a snap. Applications which use classic confinement have the same full system access as traditionally packaged applications. Classic confinement is intended as a stop-gap measure to enable developers to publish applications which need more access than the current set of interfaces enable. Over time, as more interfaces are developed, snap publishers can migrate away from classic confinement to strict.

https://docs.snapcraft.io/snap-confinement/6233


VSCode and other IDEs including intellij need classic confinement to be able to access to the system.

This is by design.

My projects are in /home/<user_name>. The console in vscode should have full access to be able to run whatever I want unrestricted.

**Comment by jackTaw88** [comment]
It is very good to have all config files of vscode in one directory (/home/user/snap/vscode/current). 

I start vscode by a script which changes the HOME path as /home/user/snap/vscode.

I can develop many different project with it. There is no any access problem. The problem is:

vscode does not use the same directories with other runtime environments. for example:

in some cases ./npm directory will be use by platfrom:
- Nodejs: /home/user/.npm
- Vscode (snap): /home/user/snap/vscode/.npm


As I sad it would be great to have all config files inside /home/user/snap/vscode directory but  that will effect other things...
